name: 'Build nodejs app and push them to registry'
description: 'Automatically build Dockerfile with recessary build arguments for NPM packages and push them to the desired ECR repository.'
branding:
  icon: 'cloud'
  color: 'pink'
inputs:
  image:
    description: 'Image repository'
    required: true
  aws-region:
    description: 'AWS Region'
    required: false
    default: 'eu-central-1'
  aws-access-key-id:
    description: 'AWS Access Key'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Key'
    required: true
  npm-auth-token:
    description: 'NPM auth token'
    required: true
  msteams-webhook:
    description: 'Microsoft Teams Webhook for notifications'
    required: false
runs:
  ## Replace that when officially supported by GitHub
  using: "includes"
  # using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Amazon ECR Login
      uses: aws-actions/amazon-ecr-login@v1
    - id: build-id
      uses: enersis/build-id@master
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build and publish container image with tag
      uses: docker/build-push-action@v2
      with:
          push: true
          context: .
          build-args: "NPM_TOKEN=${{ inputs.npm-auth-token }}"
          file: ./Dockerfile
          tags: ${{ inputs.image }}:${{ steps.build-id.outputs.id }}
